CREATE DATABASE IF NOT EXISTS Meetup;

CREATE TABLE IF NOT EXISTS Meetups
(Id INTEGER NOT NULL,
Starttime DATETIME NOT NULL,
Location VARCHAR(150) NOT NULL,
Topic VARCHAR(150) NOT NULL,
Description VARCHAR(1000) NOT NULL);

CREATE TABLE IF NOT EXISTS Statuses
(Id INTEGER NOT NULL,
Valuedata VARCHAR(50));

CREATE TABLE IF NOT EXISTS Users
(Id INTEGER NOT NULL,
Username VARCHAR(100) NOT NULL,
Birthdate DATETIME NOT NULL,
Introduction VARCHAR(500),
Avatar VARCHAR(1000),
Email VARCHAR(150));

CREATE TABLE IF NOT EXISTS MeetupRegistration
(StatusId INTEGER NOT NULL,
MeetupId INTEGER NOT NULL,
UserId INTEGER NOT NULL);